---
title: "Final Project Info"
author: "Emmeline"
date: "May 11, 2015"
output:
  html_document:
    keep_md: yes
---

Obsesity is widely viewed as one of the greatest public health problems facing Americans today. Levels of obesity have been on the rise since the 1980s at an astounding rate and currently approximately 35% of the adult population is considered [obese] (http://www.cdc.gov/obesity/data/adult.html). Obesity is of particular concern as it is associated with other disease including diabetes, hypertension, and asthma.
  Much of the literature surrounding the issue attributes high levels of obesity to a lack of access to good food and a lack of education about what good food is. Increasing nutrition education, increasing the number of bike paths, and increasing the number of food vendors selling fresh fruits and vegetables are often proposed as solutions, however, these efforts alone often fail to reduce obesity [rates] (http://www.latimes.com/local/california/la-me-0510-south-la-food-20150510-story.html#page=1). Public health officials and policy makers must consider other, possibly deeper rooted causes of obesity and other health risks if they wish to enact lasting change.
  This project seeks to examine the rates of ER visits for asthma, diabetes, and hypertension as proxies for obesity and general community health in San Francisco
by looking at race, class, and pollution as possible predictive factors. I chose to look at San Francisco as a model, because while it is considered one of the [healthiest cities] (http://www.forbes.com/sites/melaniehaiken/2014/05/30/the-20-healthiest-cities-in-america-2014/2/) it is also a city of great economic disparity and a city with neighborhoods that are often defined racially. Additionally, likely because SF is home more than its fair share of data analysts and "brogrammers" there was myriad free data available online.

  Data was collected from three sources:
  *Census data was collected from Social Explorer
  *Income, education, PM2.5, and census tract shapefiles were collected from SF Open Data
  *Disease Rates were collected from SFHIP
  
  The percentages of different races and the levels of PM2.5 were used as predictors in a multiple regression model.